2022-03-17 05:28:29.465 [error] <0.380.0> gen_server <0.380.0> terminated with reason: {socket_error,timeout}
2022-03-17 05:28:29.465 [error] <0.373.0> gen_server <0.373.0> terminated with reason: {socket_error,timeout}
2022-03-17 05:28:29.465 [error] <0.380.0> CRASH REPORT Process <0.380.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 05:28:29.465 [error] <0.373.0> CRASH REPORT Process <0.373.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 05:28:29.465 [error] <0.372.0> Supervisor {<0.372.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6>, <0.373.0>, <0.378.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:51340 -> 127.0.0.1:5672">>) at <0.380.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 05:28:29.465 [error] <0.372.0> Supervisor {<0.372.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6>, <0.373.0>, <0.378.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:51340 -> 127.0.0.1:5672">>) at <0.380.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 05:28:29.465 [error] <0.371.0> Supervisor {<0.371.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.372.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.373.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 05:28:29.465 [error] <0.371.0> Supervisor {<0.371.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.372.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.373.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 05:44:05.867 [error] <0.515.0> gen_server <0.515.0> terminated with reason: {socket_error,timeout}
2022-03-17 05:44:05.867 [error] <0.515.0> CRASH REPORT Process <0.515.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 05:44:05.868 [error] <0.510.0> Supervisor {<0.510.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7>, <0.511.0>, <0.513.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52155 -> 127.0.0.1:5672">>) at <0.515.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 05:44:05.868 [error] <0.510.0> Supervisor {<0.510.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7>, <0.511.0>, <0.513.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52155 -> 127.0.0.1:5672">>) at <0.515.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 05:44:05.868 [error] <0.511.0> gen_server <0.511.0> terminated with reason: {socket_error,timeout}
2022-03-17 05:44:05.869 [error] <0.511.0> CRASH REPORT Process <0.511.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 05:44:05.869 [error] <0.509.0> Supervisor {<0.509.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.510.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.511.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 05:44:05.869 [error] <0.509.0> Supervisor {<0.509.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.510.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.511.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 05:59:15.253 [error] <0.530.0> gen_server <0.530.0> terminated with reason: {socket_error,timeout}
2022-03-17 05:59:15.253 [error] <0.530.0> CRASH REPORT Process <0.530.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 05:59:15.253 [error] <0.525.0> Supervisor {<0.525.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.8>, <0.526.0>, <0.528.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52178 -> 127.0.0.1:5672">>) at <0.530.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 05:59:15.253 [error] <0.525.0> Supervisor {<0.525.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.8>, <0.526.0>, <0.528.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52178 -> 127.0.0.1:5672">>) at <0.530.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 05:59:15.253 [error] <0.526.0> gen_server <0.526.0> terminated with reason: {socket_error,timeout}
2022-03-17 05:59:15.253 [error] <0.526.0> CRASH REPORT Process <0.526.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 05:59:15.253 [error] <0.524.0> Supervisor {<0.524.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.525.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.526.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 05:59:15.253 [error] <0.524.0> Supervisor {<0.524.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.525.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.526.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 06:15:32.415 [error] <0.545.0> gen_server <0.545.0> terminated with reason: {socket_error,timeout}
2022-03-17 06:15:32.415 [error] <0.545.0> CRASH REPORT Process <0.545.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 06:15:32.415 [error] <0.540.0> Supervisor {<0.540.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.9>, <0.541.0>, <0.543.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52186 -> 127.0.0.1:5672">>) at <0.545.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 06:15:32.415 [error] <0.540.0> Supervisor {<0.540.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.9>, <0.541.0>, <0.543.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52186 -> 127.0.0.1:5672">>) at <0.545.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 06:15:32.415 [error] <0.541.0> gen_server <0.541.0> terminated with reason: {socket_error,timeout}
2022-03-17 06:15:32.415 [error] <0.541.0> CRASH REPORT Process <0.541.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 06:15:32.416 [error] <0.539.0> Supervisor {<0.539.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.540.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.541.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 06:15:32.416 [error] <0.539.0> Supervisor {<0.539.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.540.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.541.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 06:15:32.442 [error] <0.351.0> gen_server 'Elixir.BookingsPipeline.Broadway.Producer_0' terminated with reason: {{socket_error,timeout},{gen_server,call,[<0.541.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}},70000]}} in gen_server:call/3 line 247
2022-03-17 06:15:32.442 [error] <0.351.0> CRASH REPORT Process 'Elixir.BookingsPipeline.Broadway.Producer_0' with 0 neighbours exited with reason: {{socket_error,timeout},{gen_server,call,[<0.541.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}},70000]}} in gen_server:call/3 line 247
2022-03-17 06:15:32.442 [error] <0.350.0> Supervisor 'Elixir.BookingsPipeline.Broadway.ProducerSupervisor' had child 'Elixir.BookingsPipeline.Broadway.Producer_0' started with 'Elixir.Broadway.Topology.ProducerStage':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingsPipeline.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.351.0> exit with reason {{socket_error,timeout},{gen_server,call,[<0.541.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}},70000]}} in context child_terminated
2022-03-17 06:30:56.579 [error] <0.561.0> gen_server <0.561.0> terminated with reason: {socket_error,timeout}
2022-03-17 06:30:56.579 [error] <0.561.0> CRASH REPORT Process <0.561.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 06:30:56.580 [error] <0.556.0> Supervisor {<0.556.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.10>, <0.557.0>, <0.559.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52200 -> 127.0.0.1:5672">>) at <0.561.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 06:30:56.580 [error] <0.556.0> Supervisor {<0.556.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.10>, <0.557.0>, <0.559.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52200 -> 127.0.0.1:5672">>) at <0.561.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 06:30:56.580 [error] <0.557.0> gen_server <0.557.0> terminated with reason: {socket_error,timeout}
2022-03-17 06:30:56.580 [error] <0.557.0> CRASH REPORT Process <0.557.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 06:30:56.580 [error] <0.555.0> Supervisor {<0.555.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.556.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.557.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 06:30:56.580 [error] <0.555.0> Supervisor {<0.555.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.556.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.557.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 06:48:24.060 [error] <0.576.0> gen_server <0.576.0> terminated with reason: {socket_error,timeout}
2022-03-17 06:48:24.060 [error] <0.576.0> CRASH REPORT Process <0.576.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 06:48:24.060 [error] <0.572.0> gen_server <0.572.0> terminated with reason: {socket_error,timeout}
2022-03-17 06:48:24.061 [error] <0.572.0> CRASH REPORT Process <0.572.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 06:48:24.061 [error] <0.570.0> Supervisor {<0.570.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.571.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.572.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 06:48:24.061 [error] <0.570.0> Supervisor {<0.570.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.571.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.572.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 06:48:24.061 [error] <0.571.0> Supervisor {<0.571.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.11>, <0.572.0>, <0.574.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52216 -> 127.0.0.1:5672">>) at <0.576.0> exit with reason noproc in context shutdown_error
2022-03-17 07:05:22.164 [error] <0.591.0> gen_server <0.591.0> terminated with reason: {socket_error,timeout}
2022-03-17 07:05:22.164 [error] <0.591.0> CRASH REPORT Process <0.591.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 07:05:22.164 [error] <0.586.0> Supervisor {<0.586.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.12>, <0.587.0>, <0.589.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52222 -> 127.0.0.1:5672">>) at <0.591.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 07:05:22.164 [error] <0.586.0> Supervisor {<0.586.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.12>, <0.587.0>, <0.589.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52222 -> 127.0.0.1:5672">>) at <0.591.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 07:05:22.164 [error] <0.587.0> gen_server <0.587.0> terminated with reason: {socket_error,timeout}
2022-03-17 07:05:22.164 [error] <0.587.0> CRASH REPORT Process <0.587.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 07:05:22.164 [error] <0.585.0> Supervisor {<0.585.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.586.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.587.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 07:05:22.165 [error] <0.585.0> Supervisor {<0.585.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.586.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.587.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 07:20:59.848 [error] <0.606.0> gen_server <0.606.0> terminated with reason: {socket_error,timeout}
2022-03-17 07:20:59.848 [error] <0.606.0> CRASH REPORT Process <0.606.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 07:20:59.848 [error] <0.601.0> Supervisor {<0.601.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.13>, <0.602.0>, <0.604.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52231 -> 127.0.0.1:5672">>) at <0.606.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 07:20:59.848 [error] <0.601.0> Supervisor {<0.601.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.13>, <0.602.0>, <0.604.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52231 -> 127.0.0.1:5672">>) at <0.606.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 07:20:59.848 [error] <0.602.0> gen_server <0.602.0> terminated with reason: {socket_error,timeout}
2022-03-17 07:20:59.848 [error] <0.602.0> CRASH REPORT Process <0.602.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 07:20:59.849 [error] <0.600.0> Supervisor {<0.600.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.601.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.602.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 07:20:59.849 [error] <0.600.0> Supervisor {<0.600.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.601.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.602.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 07:37:00.131 [error] <0.621.0> gen_server <0.621.0> terminated with reason: {socket_error,timeout}
2022-03-17 07:37:00.131 [error] <0.621.0> CRASH REPORT Process <0.621.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 07:37:00.131 [error] <0.616.0> Supervisor {<0.616.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.14>, <0.617.0>, <0.619.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52243 -> 127.0.0.1:5672">>) at <0.621.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 07:37:00.132 [error] <0.616.0> Supervisor {<0.616.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.14>, <0.617.0>, <0.619.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52243 -> 127.0.0.1:5672">>) at <0.621.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 07:37:00.132 [error] <0.617.0> gen_server <0.617.0> terminated with reason: {socket_error,timeout}
2022-03-17 07:37:00.132 [error] <0.617.0> CRASH REPORT Process <0.617.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 07:37:00.133 [error] <0.615.0> Supervisor {<0.615.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.616.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.617.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 07:37:00.133 [error] <0.615.0> Supervisor {<0.615.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.616.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.617.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 07:37:00.134 [error] <0.554.0> gen_server 'Elixir.BookingsPipeline.Broadway.Producer_0' terminated with reason: {{socket_error,timeout},{gen_server,call,[<0.617.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}},70000]}} in gen_server:call/3 line 247
2022-03-17 07:37:00.134 [error] <0.554.0> CRASH REPORT Process 'Elixir.BookingsPipeline.Broadway.Producer_0' with 0 neighbours exited with reason: {{socket_error,timeout},{gen_server,call,[<0.617.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}},70000]}} in gen_server:call/3 line 247
2022-03-17 07:37:00.134 [error] <0.350.0> Supervisor 'Elixir.BookingsPipeline.Broadway.ProducerSupervisor' had child 'Elixir.BookingsPipeline.Broadway.Producer_0' started with 'Elixir.Broadway.Topology.ProducerStage':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingsPipeline.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.554.0> exit with reason {{socket_error,timeout},{gen_server,call,[<0.617.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}},70000]}} in context child_terminated
2022-03-17 07:54:32.857 [error] <0.637.0> gen_server <0.637.0> terminated with reason: {socket_error,timeout}
2022-03-17 07:54:32.858 [error] <0.637.0> CRASH REPORT Process <0.637.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 07:54:32.858 [error] <0.632.0> Supervisor {<0.632.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.15>, <0.633.0>, <0.635.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52264 -> 127.0.0.1:5672">>) at <0.637.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 07:54:32.858 [error] <0.632.0> Supervisor {<0.632.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.15>, <0.633.0>, <0.635.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52264 -> 127.0.0.1:5672">>) at <0.637.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 07:54:32.858 [error] <0.633.0> gen_server <0.633.0> terminated with reason: {socket_error,timeout}
2022-03-17 07:54:32.858 [error] <0.633.0> CRASH REPORT Process <0.633.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 07:54:32.858 [error] <0.631.0> Supervisor {<0.631.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.632.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.633.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 07:54:32.858 [error] <0.631.0> Supervisor {<0.631.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.632.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.633.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 07:54:32.964 [error] <0.630.0> gen_server 'Elixir.BookingsPipeline.Broadway.Producer_0' terminated with reason: {{socket_error,timeout},{gen_server,call,[<0.633.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}},70000]}} in gen_server:call/3 line 247
2022-03-17 07:54:32.964 [error] <0.630.0> CRASH REPORT Process 'Elixir.BookingsPipeline.Broadway.Producer_0' with 0 neighbours exited with reason: {{socket_error,timeout},{gen_server,call,[<0.633.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}},70000]}} in gen_server:call/3 line 247
2022-03-17 07:54:32.965 [error] <0.350.0> Supervisor 'Elixir.BookingsPipeline.Broadway.ProducerSupervisor' had child 'Elixir.BookingsPipeline.Broadway.Producer_0' started with 'Elixir.Broadway.Topology.ProducerStage':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingsPipeline.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.630.0> exit with reason {{socket_error,timeout},{gen_server,call,[<0.633.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}},70000]}} in context child_terminated
2022-03-17 08:10:58.179 [error] <0.653.0> gen_server <0.653.0> terminated with reason: {socket_error,timeout}
2022-03-17 08:10:58.179 [error] <0.653.0> CRASH REPORT Process <0.653.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 08:10:58.180 [error] <0.648.0> Supervisor {<0.648.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.16>, <0.649.0>, <0.651.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52266 -> 127.0.0.1:5672">>) at <0.653.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 08:10:58.180 [error] <0.648.0> Supervisor {<0.648.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.16>, <0.649.0>, <0.651.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52266 -> 127.0.0.1:5672">>) at <0.653.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 08:10:58.180 [error] <0.649.0> gen_server <0.649.0> terminated with reason: {socket_error,timeout}
2022-03-17 08:10:58.180 [error] <0.649.0> CRASH REPORT Process <0.649.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 08:10:58.181 [error] <0.647.0> Supervisor {<0.647.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.648.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.649.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 08:10:58.181 [error] <0.647.0> Supervisor {<0.647.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.648.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.649.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 08:29:01.710 [error] <0.668.0> gen_server <0.668.0> terminated with reason: {socket_error,timeout}
2022-03-17 08:29:01.710 [error] <0.668.0> CRASH REPORT Process <0.668.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 08:29:01.710 [error] <0.664.0> gen_server <0.664.0> terminated with reason: {socket_error,timeout}
2022-03-17 08:29:01.710 [error] <0.664.0> CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 08:29:01.711 [error] <0.662.0> Supervisor {<0.662.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.663.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.664.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 08:29:01.711 [error] <0.662.0> Supervisor {<0.662.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.663.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.664.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 08:29:01.711 [error] <0.663.0> Supervisor {<0.663.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.17>, <0.664.0>, <0.666.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52268 -> 127.0.0.1:5672">>) at <0.668.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 08:29:01.711 [error] <0.663.0> Supervisor {<0.663.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.17>, <0.664.0>, <0.666.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52268 -> 127.0.0.1:5672">>) at <0.668.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 08:46:26.309 [error] <0.683.0> gen_server <0.683.0> terminated with reason: {socket_error,timeout}
2022-03-17 08:46:26.309 [error] <0.683.0> CRASH REPORT Process <0.683.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 08:46:26.310 [error] <0.679.0> gen_server <0.679.0> terminated with reason: {socket_error,timeout}
2022-03-17 08:46:26.310 [error] <0.679.0> CRASH REPORT Process <0.679.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 08:46:26.310 [error] <0.677.0> Supervisor {<0.677.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.678.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.679.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 08:46:26.311 [error] <0.677.0> Supervisor {<0.677.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.678.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.679.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 08:46:26.311 [error] <0.678.0> Supervisor {<0.678.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.18>, <0.679.0>, <0.681.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52293 -> 127.0.0.1:5672">>) at <0.683.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 08:46:26.311 [error] <0.678.0> Supervisor {<0.678.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.18>, <0.679.0>, <0.681.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52293 -> 127.0.0.1:5672">>) at <0.683.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 08:51:40.201 [error] <0.698.0> gen_server <0.698.0> terminated with reason: {socket_error,timeout}
2022-03-17 08:51:40.201 [error] <0.698.0> CRASH REPORT Process <0.698.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 08:51:40.201 [error] <0.692.0> Supervisor {<0.692.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.19>, <0.693.0>, <0.696.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52301 -> 127.0.0.1:5672">>) at <0.698.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 08:51:40.201 [error] <0.692.0> Supervisor {<0.692.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.19>, <0.693.0>, <0.696.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52301 -> 127.0.0.1:5672">>) at <0.698.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 08:51:40.201 [error] <0.693.0> gen_server <0.693.0> terminated with reason: {socket_error,timeout}
2022-03-17 08:51:40.201 [error] <0.693.0> CRASH REPORT Process <0.693.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 08:51:40.201 [error] <0.691.0> Supervisor {<0.691.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.692.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.693.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 08:51:40.202 [error] <0.691.0> Supervisor {<0.691.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.692.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.693.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 09:04:00.677 [error] <0.713.0> gen_server <0.713.0> terminated with reason: {socket_error,timeout}
2022-03-17 09:04:00.677 [error] <0.713.0> CRASH REPORT Process <0.713.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 09:04:00.677 [error] <0.708.0> Supervisor {<0.708.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.20>, <0.709.0>, <0.711.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52308 -> 127.0.0.1:5672">>) at <0.713.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 09:04:00.677 [error] <0.708.0> Supervisor {<0.708.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.20>, <0.709.0>, <0.711.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52308 -> 127.0.0.1:5672">>) at <0.713.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 09:04:00.677 [error] <0.709.0> gen_server <0.709.0> terminated with reason: {socket_error,timeout}
2022-03-17 09:04:00.677 [error] <0.709.0> CRASH REPORT Process <0.709.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 09:04:00.678 [error] <0.707.0> Supervisor {<0.707.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.708.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.709.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 09:04:00.678 [error] <0.707.0> Supervisor {<0.707.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.708.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.709.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 09:04:00.680 [error] <0.646.0> gen_server 'Elixir.BookingsPipeline.Broadway.Producer_0' terminated with reason: {{socket_error,timeout},{gen_server,call,[<0.709.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}},70000]}} in gen_server:call/3 line 247
2022-03-17 09:04:00.680 [error] <0.646.0> CRASH REPORT Process 'Elixir.BookingsPipeline.Broadway.Producer_0' with 0 neighbours exited with reason: {{socket_error,timeout},{gen_server,call,[<0.709.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}},70000]}} in gen_server:call/3 line 247
2022-03-17 09:04:00.680 [error] <0.350.0> Supervisor 'Elixir.BookingsPipeline.Broadway.ProducerSupervisor' had child 'Elixir.BookingsPipeline.Broadway.Producer_0' started with 'Elixir.Broadway.Topology.ProducerStage':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingsPipeline.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.646.0> exit with reason {{socket_error,timeout},{gen_server,call,[<0.709.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}},70000]}} in context child_terminated
2022-03-17 09:05:49.933 [error] <0.729.0> gen_server <0.729.0> terminated with reason: {socket_error,timeout}
2022-03-17 09:05:49.933 [error] <0.725.0> gen_server <0.725.0> terminated with reason: {socket_error,timeout}
2022-03-17 09:05:49.933 [error] <0.725.0> CRASH REPORT Process <0.725.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 09:05:49.933 [error] <0.729.0> CRASH REPORT Process <0.729.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 09:05:49.934 [error] <0.723.0> Supervisor {<0.723.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.724.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.725.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 09:05:49.934 [error] <0.723.0> Supervisor {<0.723.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.724.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.725.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 09:05:49.935 [error] <0.724.0> Supervisor {<0.724.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.21>, <0.725.0>, <0.727.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52316 -> 127.0.0.1:5672">>) at <0.729.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 09:05:49.935 [error] <0.724.0> Supervisor {<0.724.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.21>, <0.725.0>, <0.727.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:52316 -> 127.0.0.1:5672">>) at <0.729.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 21:05:58.034 [error] <0.341.0> gen_server <0.341.0> terminated with reason: {socket_error,timeout}
2022-03-17 21:05:58.034 [error] <0.334.0> gen_server <0.334.0> terminated with reason: {socket_error,timeout}
2022-03-17 21:05:58.034 [error] <0.341.0> CRASH REPORT Process <0.341.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 21:05:58.034 [error] <0.334.0> CRASH REPORT Process <0.334.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 21:05:58.034 [error] <0.333.0> Supervisor {<0.333.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6>, <0.334.0>, <0.339.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60854 -> 127.0.0.1:5672">>) at <0.341.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 21:05:58.034 [error] <0.333.0> Supervisor {<0.333.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6>, <0.334.0>, <0.339.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60854 -> 127.0.0.1:5672">>) at <0.341.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 21:05:58.034 [error] <0.332.0> Supervisor {<0.332.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.333.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.334.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 21:05:58.035 [error] <0.332.0> Supervisor {<0.332.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.333.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.334.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 21:36:22.138 [error] <0.385.0> gen_server <0.385.0> terminated with reason: {socket_error,timeout}
2022-03-17 21:36:22.139 [error] <0.385.0> CRASH REPORT Process <0.385.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 21:36:22.140 [error] <0.381.0> gen_server <0.381.0> terminated with reason: {socket_error,timeout}
2022-03-17 21:36:22.140 [error] <0.381.0> CRASH REPORT Process <0.381.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 21:36:22.140 [error] <0.380.0> Supervisor {<0.380.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.8>, <0.381.0>, <0.383.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:61010 -> 127.0.0.1:5672">>) at <0.385.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 21:36:22.140 [error] <0.380.0> Supervisor {<0.380.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.8>, <0.381.0>, <0.383.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:61010 -> 127.0.0.1:5672">>) at <0.385.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 21:36:22.151 [error] <0.379.0> Supervisor {<0.379.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.380.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.381.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 21:36:22.151 [error] <0.379.0> Supervisor {<0.379.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.380.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.381.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 21:52:08.468 [error] <0.407.0> gen_server <0.407.0> terminated with reason: {socket_error,timeout}
2022-03-17 21:52:08.469 [error] <0.407.0> CRASH REPORT Process <0.407.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 21:52:08.472 [error] <0.402.0> Supervisor {<0.402.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.9>, <0.403.0>, <0.405.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63912 -> 127.0.0.1:5672">>) at <0.407.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 21:52:08.472 [error] <0.402.0> Supervisor {<0.402.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.9>, <0.403.0>, <0.405.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63912 -> 127.0.0.1:5672">>) at <0.407.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 21:52:08.472 [error] <0.403.0> gen_server <0.403.0> terminated with reason: {socket_error,timeout}
2022-03-17 21:52:08.472 [error] <0.403.0> CRASH REPORT Process <0.403.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 21:52:08.472 [error] <0.401.0> Supervisor {<0.401.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.402.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.403.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 21:52:08.472 [error] <0.401.0> Supervisor {<0.401.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.402.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.403.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 22:09:04.014 [error] <0.422.0> gen_server <0.422.0> terminated with reason: {socket_error,timeout}
2022-03-17 22:09:04.024 [error] <0.422.0> CRASH REPORT Process <0.422.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 22:09:04.024 [error] <0.417.0> Supervisor {<0.417.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.10>, <0.418.0>, <0.420.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:64016 -> 127.0.0.1:5672">>) at <0.422.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 22:09:04.024 [error] <0.417.0> Supervisor {<0.417.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.10>, <0.418.0>, <0.420.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:64016 -> 127.0.0.1:5672">>) at <0.422.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 22:09:04.024 [error] <0.418.0> gen_server <0.418.0> terminated with reason: {socket_error,timeout}
2022-03-17 22:09:04.024 [error] <0.418.0> CRASH REPORT Process <0.418.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 22:09:04.025 [error] <0.416.0> Supervisor {<0.416.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.417.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.418.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 22:09:04.025 [error] <0.416.0> Supervisor {<0.416.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.417.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.418.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 22:09:04.031 [error] <0.416.0> Supervisor {<0.416.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.417.0> exit with reason shutdown in context shutdown_error
2022-03-17 22:22:30.663 [error] <0.437.0> gen_server <0.437.0> terminated with reason: {socket_error,timeout}
2022-03-17 22:22:30.663 [error] <0.437.0> CRASH REPORT Process <0.437.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 22:22:30.664 [error] <0.432.0> Supervisor {<0.432.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.11>, <0.433.0>, <0.435.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:64100 -> 127.0.0.1:5672">>) at <0.437.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 22:22:30.664 [error] <0.432.0> Supervisor {<0.432.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.11>, <0.433.0>, <0.435.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:64100 -> 127.0.0.1:5672">>) at <0.437.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 22:22:30.664 [error] <0.433.0> gen_server <0.433.0> terminated with reason: {socket_error,timeout}
2022-03-17 22:22:30.664 [error] <0.433.0> CRASH REPORT Process <0.433.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 22:22:30.665 [error] <0.431.0> Supervisor {<0.431.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.432.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.433.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 22:22:30.665 [error] <0.431.0> Supervisor {<0.431.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.432.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.433.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 22:22:30.694 [error] <0.312.0> gen_server 'Elixir.BookingsPipeline.Broadway.Producer_0' terminated with reason: {{socket_error,timeout},{gen_server,call,[<0.433.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}},70000]}} in gen_server:call/3 line 247
2022-03-17 22:22:30.694 [error] <0.312.0> CRASH REPORT Process 'Elixir.BookingsPipeline.Broadway.Producer_0' with 0 neighbours exited with reason: {{socket_error,timeout},{gen_server,call,[<0.433.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}},70000]}} in gen_server:call/3 line 247
2022-03-17 22:22:30.694 [error] <0.311.0> Supervisor 'Elixir.BookingsPipeline.Broadway.ProducerSupervisor' had child 'Elixir.BookingsPipeline.Broadway.Producer_0' started with 'Elixir.Broadway.Topology.ProducerStage':start_link([{broadway,[{hibernate_after,15000},{batchers,[]},{context,context_not_set},{resubscribe_interval,...},...]},...], 0, [{name,'Elixir.BookingsPipeline.Broadway.Producer_0'},{hibernate_after,15000}]) at <0.312.0> exit with reason {{socket_error,timeout},{gen_server,call,[<0.433.0>,{command,{close,{'connection.close',200,<<"Goodbye">>,0,0},70000}},70000]}} in context child_terminated
2022-03-17 22:27:11.176 [error] <0.457.0> gen_server <0.457.0> terminated with reason: {socket_error,timeout}
2022-03-17 22:27:11.176 [error] <0.457.0> CRASH REPORT Process <0.457.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 22:27:11.176 [error] <0.452.0> Supervisor {<0.452.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.12>, <0.453.0>, <0.455.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49158 -> 127.0.0.1:5672">>) at <0.457.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 22:27:11.176 [error] <0.452.0> Supervisor {<0.452.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.12>, <0.453.0>, <0.455.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49158 -> 127.0.0.1:5672">>) at <0.457.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 22:27:11.176 [error] <0.453.0> gen_server <0.453.0> terminated with reason: {socket_error,timeout}
2022-03-17 22:27:11.176 [error] <0.453.0> CRASH REPORT Process <0.453.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 22:27:11.176 [error] <0.451.0> Supervisor {<0.451.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.452.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.453.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 22:27:11.176 [error] <0.451.0> Supervisor {<0.451.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.452.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.453.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 22:33:00.510 [error] <0.472.0> gen_server <0.472.0> terminated with reason: {socket_error,timeout}
2022-03-17 22:33:00.510 [error] <0.472.0> CRASH REPORT Process <0.472.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 22:33:00.510 [error] <0.467.0> Supervisor {<0.467.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.13>, <0.468.0>, <0.470.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49266 -> 127.0.0.1:5672">>) at <0.472.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 22:33:00.510 [error] <0.467.0> Supervisor {<0.467.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.13>, <0.468.0>, <0.470.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49266 -> 127.0.0.1:5672">>) at <0.472.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 22:33:00.510 [error] <0.468.0> gen_server <0.468.0> terminated with reason: {socket_error,timeout}
2022-03-17 22:33:00.510 [error] <0.468.0> CRASH REPORT Process <0.468.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 22:33:00.510 [error] <0.466.0> Supervisor {<0.466.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.467.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.468.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 22:33:00.510 [error] <0.466.0> Supervisor {<0.466.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.467.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.468.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 22:47:27.260 [error] <0.487.0> gen_server <0.487.0> terminated with reason: {socket_error,timeout}
2022-03-17 22:47:27.261 [error] <0.487.0> CRASH REPORT Process <0.487.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 22:47:27.261 [error] <0.483.0> gen_server <0.483.0> terminated with reason: {socket_error,timeout}
2022-03-17 22:47:27.264 [error] <0.483.0> CRASH REPORT Process <0.483.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 22:47:27.265 [error] <0.482.0> Supervisor {<0.482.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.14>, <0.483.0>, <0.485.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49423 -> 127.0.0.1:5672">>) at <0.487.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 22:47:27.265 [error] <0.482.0> Supervisor {<0.482.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.14>, <0.483.0>, <0.485.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49423 -> 127.0.0.1:5672">>) at <0.487.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 22:47:27.265 [error] <0.481.0> Supervisor {<0.481.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.482.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.483.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 22:47:27.265 [error] <0.481.0> Supervisor {<0.481.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.482.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.483.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 22:50:16.322 [error] <0.502.0> gen_server <0.502.0> terminated with reason: {socket_error,timeout}
2022-03-17 22:50:16.322 [error] <0.502.0> CRASH REPORT Process <0.502.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 22:50:16.323 [error] <0.497.0> Supervisor {<0.497.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.15>, <0.498.0>, <0.500.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49510 -> 127.0.0.1:5672">>) at <0.502.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 22:50:16.323 [error] <0.497.0> Supervisor {<0.497.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.15>, <0.498.0>, <0.500.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49510 -> 127.0.0.1:5672">>) at <0.502.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 22:50:16.324 [error] <0.498.0> gen_server <0.498.0> terminated with reason: {socket_error,timeout}
2022-03-17 22:50:16.324 [error] <0.498.0> CRASH REPORT Process <0.498.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 22:50:16.325 [error] <0.496.0> Supervisor {<0.496.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.497.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.498.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 22:50:16.325 [error] <0.496.0> Supervisor {<0.496.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.497.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.498.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 23:04:35.383 [error] <0.517.0> gen_server <0.517.0> terminated with reason: {socket_error,timeout}
2022-03-17 23:04:35.383 [error] <0.517.0> CRASH REPORT Process <0.517.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 23:04:35.383 [error] <0.512.0> Supervisor {<0.512.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.16>, <0.513.0>, <0.515.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49593 -> 127.0.0.1:5672">>) at <0.517.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 23:04:35.384 [error] <0.512.0> Supervisor {<0.512.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.16>, <0.513.0>, <0.515.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49593 -> 127.0.0.1:5672">>) at <0.517.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 23:04:35.384 [error] <0.513.0> gen_server <0.513.0> terminated with reason: {socket_error,timeout}
2022-03-17 23:04:35.384 [error] <0.513.0> CRASH REPORT Process <0.513.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 23:04:35.384 [error] <0.511.0> Supervisor {<0.511.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.512.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.513.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 23:04:35.384 [error] <0.511.0> Supervisor {<0.511.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.512.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.513.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 23:14:16.851 [error] <0.532.0> gen_server <0.532.0> terminated with reason: {socket_error,timeout}
2022-03-17 23:14:16.854 [error] <0.532.0> CRASH REPORT Process <0.532.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 23:14:16.854 [error] <0.528.0> gen_server <0.528.0> terminated with reason: {socket_error,timeout}
2022-03-17 23:14:16.854 [error] <0.528.0> CRASH REPORT Process <0.528.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-03-17 23:14:16.855 [error] <0.526.0> Supervisor {<0.526.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.527.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.528.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 23:14:16.855 [error] <0.526.0> Supervisor {<0.526.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.527.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.528.0> exit with reason reached_max_restart_intensity in context shutdown
2022-03-17 23:14:16.855 [error] <0.527.0> Supervisor {<0.527.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.17>, <0.528.0>, <0.530.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49703 -> 127.0.0.1:5672">>) at <0.532.0> exit with reason {socket_error,timeout} in context child_terminated
2022-03-17 23:14:16.855 [error] <0.527.0> Supervisor {<0.527.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.17>, <0.528.0>, <0.530.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49703 -> 127.0.0.1:5672">>) at <0.532.0> exit with reason reached_max_restart_intensity in context shutdown
